import shortuuid

from setup import *
from logger import LOGGER

import pandas as pd
import os
import json
import spacy
import subprocess
import nltk
import string
import random
import numpy as np
from typing import Dict, List, Union
from nltk.corpus import stopwords
from tqdm import tqdm
from datetime import datetime
from spacy.tokens import Doc
from string import punctuation
import itertools
import warnings
import math
warnings.filterwarnings('ignore')
from utils import check_mention_attributes
import colorcet as cc
import dask_ml.feature_extraction.text
import datashader as ds
from datashader.utils import export_image
from openTSNE import TSNE
from sklearn.decomposition import TruncatedSVD
from sentence_transformers import SentenceTransformer
from setup import *
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt


nltk.download('stopwords')

MUC = "_MUC"
B3 = "_B3"
CEAF_M = "_CEAF_M"
CEAF_E = "_CEAF_E"
BLANC = "_BLANC"
CONLL = "_CONLL"
P = "P"
R = "R"
F1 = "F1"
TRUE_LABEL, PRED_LABEL = "label_true", "label_pred"
SPLIT = "split"

COLORS = {
    "CD2CR": "#1F77B4",
    "ECBplus": "#FF7F0E",
    "ECBplusMETAm": "#2CA02C",
    "FCC": "#D62728",
    "GVC": "#9467BD",
    "HyperCoref": "#8C564B",
    "MEANTIME": "#E377C2",
    "NewsWCL50": "#7F7F7F",
    "NIdent": "#BCBD22",
    "NP4E": "#17BECF",
    "WECEng": "#8DB0DF",
    "CEREC": "#FFBB78"
}

CORRECTED_LABELS = {
    "CD2CR": "CD2CR",
    "ECBplus": "ECB+",
    "ECBplusMETAm": "ECB+METAm",
    "FCC": "FCC-T",
    "GVC": "GVC",
    "HyperCoref": "HyperCoref_exp",
    "MEANTIME": "MEANTIME-eng",
    "NewsWCL50": "NewsWCL50r",
    "NIdent": "NIdent_en-cd",
    "NP4E": "NP4E_cd",
    "WECEng": "WEC-Eng",
    "CEREC": "CEREC_exp"
}


def phrasing_diversity_calc(mentions: List[Dict]) -> float:
    """
    Calculates a metric that represents phrasing complexity of an entity, i.e., how various is the wording of the
    phrases referring to this entity. For more details see LREC paper
    Returns:
        Internal headword-based structure, value of the phrasing complexity

    a format of members from the json for vis:
    [
        {
            "sentence": 0,
            "mention_id": ll0009,
            "doc_id: 0,
            "tokens_number": [6, 7, 8, 9, 10, 11, 12, 13, 14],
            "tokens_text": ["Trump", "in", "broad", "quest", "on", "Russia", "ties", "and", "obstruction"],
            "tokens_str": "Trump in broad quest on Russia ties and obstruction",
            "mention_head_id": 6,
            "mention_head": "Trump"
        }
    ]
    """
    headwords_phrase_tree = {}
    for mention in mentions:
        mention_wo_stopwords = [w for w in mention[TOKENS_TEXT]
                                 if w not in string.punctuation and w not in stopwords.words("english")]

        if not len(mention_wo_stopwords):
            continue

        mention_wordset = frozenset(mention_wo_stopwords)

        if mention[MENTION_HEAD] not in headwords_phrase_tree:
            headwords_phrase_tree[mention[MENTION_HEAD]] = {"set": {mention_wordset},
                                                            "list": [mention_wo_stopwords]}
        else:
            # set ensures unique phrases
            headwords_phrase_tree[mention[MENTION_HEAD]]["set"].add(mention_wordset)
            # list keeps actual number of phrase occurence
            headwords_phrase_tree[mention[MENTION_HEAD]]["list"].append(mention_wo_stopwords)

    sets = []
    fractions = []
    for head, head_properties in headwords_phrase_tree.items():
        fractions.append(len(head_properties["set"]) / (len(head_properties["list"])))
        sets.append(len(head_properties["set"]))

    score = np.sum(np.array(fractions)) * np.sum(np.array(sets)) / len(mentions) if len(mentions) > 1 else 1
    return float(format(score, '.3f'))


def compute_mtld(tokens: List[str], threshold=0.72, do_bidir=True):
    # the implemented metric from https://link.springer.com/article/10.3758/BRM.42.2.381 generated by GPT5

    def mtld_pass(tokens):
        types = set()
        token_count = 0
        factor_lengths = []
        start = 0

        for i, word in enumerate(tokens):
            token_count += 1
            types.add(word)

            ttr = len(types) / token_count
            if ttr <= threshold:
                # close a factor
                factor_lengths.append(token_count)
                # reset
                types = set()
                token_count = 0

        # handle partial factor
        if token_count > 0:
            # scaled partial length = token_count * (something depending on how close to threshold)
            # the paper defines this more exactly; you scale by how far TTR got toward threshold
            # Let final_ttr = len(types) / token_count
            final_ttr = len(types) / token_count
            # scale factor: token_count * ((final_ttr - threshold)/(1 - threshold))
            scaled = token_count * ((final_ttr - threshold) / (1 - threshold))
            factor_lengths.append(scaled)

        return sum(factor_lengths) / len(factor_lengths)

    forward = mtld_pass(tokens)
    if do_bidir:
        backward = mtld_pass(list(reversed(tokens)))
        return (forward + backward) / 2
    else:
        return forward


def conll_lemma_baseline(mentions: List[dict], subtopics: bool = True, return_only_f1: bool = False) -> Union[float, dict]:
    """
    Calculates ConLL F1 for a simple same-lemma CDCR baseline. Uses official perl script from CoNLL.
    Args:
        mentions: a list of mentions

    Returns: float, calculated F1 CoNll
    """
    resolved_mentions_dict = {}
    pred_true_df = pd.DataFrame()

    for mention in mentions:
        if subtopics:
            aggr_level = mention[SUBTOPIC_ID]
        else:
            aggr_level = mention[TOPIC_ID]

        if aggr_level not in resolved_mentions_dict:
            resolved_mentions_dict[aggr_level] = {}

        if mention[MENTION_HEAD_LEMMA] not in resolved_mentions_dict[aggr_level]:
            resolved_mentions_dict[aggr_level][mention[MENTION_HEAD_LEMMA]] = []

        resolved_mentions_dict[aggr_level][mention[MENTION_HEAD_LEMMA]].append(mention[MENTION_ID])

        pred_true_df = pd.concat([pred_true_df, pd.DataFrame({
            TRUE_LABEL: mention[COREF_CHAIN]
        }, index=[mention[MENTION_ID]])], axis=0)

    pred_true_df[PRED_LABEL] = [0] * len(pred_true_df)
    # assign predicted lavels
    for i, (topic, pred_labels_dict) in enumerate(resolved_mentions_dict.items()):
        for lemma, mentions in pred_labels_dict.items():
            for m in mentions:
                pred_true_df.loc[m, PRED_LABEL] = f"{topic}_{lemma}"

    # case for only gold mentions
    general_tag = "CDCR/cdcr_topic"
    in_str = f'#begin document ({general_tag}); part 000\n'
    out_str = f'#begin document ({general_tag}); part 000\n'

    true_label_ids_dict = {v: i for i, v in enumerate(set(pred_true_df[TRUE_LABEL].values))}
    pred_label_ids_dict = {v: i for i, v in enumerate(set(pred_true_df[PRED_LABEL].values))}
    for index_, row in pred_true_df.iterrows():
        in_str += f'{general_tag}\t({str(true_label_ids_dict[row[TRUE_LABEL]])})\n'
        out_str += f'{general_tag}\t({str(pred_label_ids_dict[row[PRED_LABEL]])})\n'

    in_str += "#end document\n"
    out_str += "#end document\n"
    with open(os.path.join(TMP_PATH, "key.key_conll"), "w") as file:
        file.write(in_str)
    with open(os.path.join(TMP_PATH, "response.response_conll"), "w") as file:
        file.write(out_str)
    result_file = os.path.join(TMP_PATH, "conll_res.txt")

    scorer_command = (f'perl {os.path.join(os.getcwd(), "scorer", "scorer.pl")} '
                      f'all {os.path.join(TMP_PATH, "key.key_conll")} '
                      f'{os.path.join(TMP_PATH, "response.response_conll")} none > {result_file} \n')

    processes = []
    # LOGGER.info('Run CoNLL scorer perl command for CDCR')
    processes.append(subprocess.Popen(scorer_command, shell=True))
    while processes:
        status = processes[0].poll()
        if status is not None:
            processes.pop(0)

    # LOGGER.info('Running CoNLL scorers has been completed.')

    f1_dict = {}
    metrics_list = [MUC, B3, CEAF_M, CEAF_E, BLANC]
    params = [R, P, F1]
    i = 0
    with open(result_file, "r") as ins:
        for line in ins:
            new_line = line.strip()
            if new_line.find('F1:') != -1:
                if i >= len(metrics_list):
                    break
                f1_dict[metrics_list[i]] = {}
                if new_line.find('Coreference') != -1:
                    j = 0
                    for value in new_line.replace("\t", " ").split(' '):
                        if "%" not in value:
                            continue
                        param = params[j]
                        f1_dict[metrics_list[i]][param] = round(float(value[:-1]), 2)
                        j += 1
                    i += 1

    # metrics_df = pd.DataFrame()
    avg_f1 = []
    # conll_count = 0
    output_dict = {}
    for metrics_name, metrics_vals in f1_dict.items():
        if metrics_name not in [MUC, B3, CEAF_E]:
            continue

        avg_f1.append(metrics_vals[F1])
        for m, v in metrics_vals.items():
            output_dict[m + metrics_name] = float(format(v, '.3f'))

    if len(avg_f1):
        f1_conll = np.mean(avg_f1)
    else:
        LOGGER.warning(f'CoNLL score was not calculated. Most likely, perl is not installed.')
        f1_conll = 0

    if return_only_f1:
        return float(format(f1_conll, '.3f'))

    output_dict[F1 + CONLL] = float(format(f1_conll, '.3f'))
    return output_dict


def create_summary(datasets: dict = None, doc_whitelist: List[str] = None, only_events: bool = False):
    """
    The script computes statistics and metrics about the datasets. A dialog window allows executing the script over one dataset per
    run or for all at the same time.
    Args:
        compute_f1: use same-lemma baseline as a metric for the lexical diversity.

    Returns:

    """
    if datasets is None:
        for i, dataset in enumerate(list(DIRECTORIES_TO_SUMMARIZE)):
            print(f'{i}: {dataset.split("-")[0]}')

        input_str = input("List dataset IDs with comma separation which to include into the summary or print \"all\" to summarize all: ")
        if "all" in input_str:
            selected_dir_to_summarize = list(DIRECTORIES_TO_SUMMARIZE.items())
        else:
            selected_dataset_ids = [int(part.strip()) for part in input_str.split(',')]
            selected_dir_to_summarize = [list(DIRECTORIES_TO_SUMMARIZE.items())[i] for i in selected_dataset_ids]
    else:
        selected_dir_to_summarize = list(datasets.items())

    LOGGER.info(f'Selected dataset to summarize: {selected_dir_to_summarize}')

    summary_df = pd.DataFrame()
    chain_df_all = pd.DataFrame()
    now_ = datetime.now()
    chains_file_name = f'{now_.strftime("%Y-%m-%d_%H-%M-%S")}_{SUMMARY_CHAINS_CSV}'

    # read annotated mentions and corresponding texts
    for dataset_name, dataset_folder in selected_dir_to_summarize:
        all_mentions_list = []
        mentions_df = pd.DataFrame()

        split_df = pd.DataFrame()

        LOGGER.info(f'Reading files with mentions for {dataset_name} dataset...')
        for mention_type, file_name in zip([EVENT, ENTITY], [MENTIONS_EVENTS_JSON, MENTIONS_ENTITIES_JSON]):

            if only_events and mention_type == ENTITY:
                continue

            # read mentions
            for split in ["train", "val", "test"]:
                full_filename = os.path.join(dataset_folder, split, file_name)
                LOGGER.info(f'Processing {full_filename}...')
                with open(full_filename, encoding='utf-8', mode='r') as file:
                    mentions_read_list = json.load(file)

                mentions_read_list_clean = []

                for mention in mentions_read_list:
                    # enforced unique mentions
                    mention[MENTION_ID] = f'{mention[MENTION_ID]}_{shortuuid.uuid()[:6]}'
                    # make sure that there is no backslashes
                    mention[COREF_CHAIN] = mention[COREF_CHAIN].replace("/", "-")
                    if LANGUAGE not in mention:
                        mention[LANGUAGE] = "english"
                    if SPLIT not in mention:
                        mention[SPLIT] = split

                    if doc_whitelist is not None:
                        if mention[DOC] not in doc_whitelist:
                            continue
                    mentions_read_list_clean.append(mention)

                df_tmp = pd.DataFrame(mentions_read_list_clean, index=list(range(len(mentions_read_list_clean))))
                df_tmp[TYPE] = [mention_type] * len(df_tmp)
                # kick out "prep" from the name
                df_tmp[DATASET_NAME] = [dataset_name.split("-")[0]] * len(df_tmp)
                mentions_df = pd.concat([mentions_df, df_tmp], ignore_index=True, axis = 0)
                all_mentions_list.extend(mentions_read_list_clean)
                if len(df_tmp):
                    split_df = pd.concat([split_df, df_tmp[[CONLL_DOC_KEY, SPLIT]].drop_duplicates()])
        split_df.drop_duplicates(inplace=True)
        mentions_df.set_index(MENTION_ID, inplace=True)

        preprocessed_df = pd.read_parquet(os.path.join(dataset_folder, DOCUMENTS_ALL_PARQUET), engine="pyarrow")
        # read texts (conll format)
        if SPLIT not in preprocessed_df.columns:
            df_conll = pd.merge(left=preprocessed_df, right=split_df, left_on=TOPIC_SUBTOPIC_DOC, right_on=CONLL_DOC_KEY, how="left")
            df_conll = df_conll.reset_index(drop=True)
        else:
            df_conll = preprocessed_df
        df_conll.rename({TOPIC_SUBTOPIC: TOPIC_SUBTOPIC_DOC}, inplace=True)

        # calculate statistics about the chains
        chain_df = pd.DataFrame(columns=[COREF_CHAIN, DATASET_NAME, SPLIT, LANGUAGE, MENTIONS])
        chain_df = pd.concat([chain_df, mentions_df[[COREF_CHAIN, DATASET_NAME, DOC_ID]].groupby([COREF_CHAIN,
                         DATASET_NAME]).count().rename(columns={DOC_ID: MENTIONS}).reset_index()], axis=0)

        chain_df = pd.concat([chain_df, mentions_df[[COREF_CHAIN, DATASET_NAME, SPLIT, DOC_ID]].groupby([COREF_CHAIN, DATASET_NAME,
                                           SPLIT]).count().rename(columns={DOC_ID: MENTIONS}).reset_index()], axis=0)
        if len(set(mentions_df[LANGUAGE].values)) > 1:
            chain_df = pd.concat([chain_df, mentions_df[[COREF_CHAIN, DATASET_NAME, LANGUAGE, DOC_ID]].groupby([COREF_CHAIN, DATASET_NAME,
                            LANGUAGE]).count().rename(columns={DOC_ID: MENTIONS}).reset_index()], axis=0)
        chain_df.fillna("", inplace=True)
        chain_df["composite_chain_id"] = chain_df.apply(lambda x: f'{x[COREF_CHAIN].replace("/", "-")}/{x[DATASET_NAME]}/{x[SPLIT]}/{x[LANGUAGE]}', axis=1)
        chain_df = chain_df.set_index("composite_chain_id")
        chain_df[PHRASING_DIVERSITY] = [0.0] * len(chain_df)
        chain_df[UNIQUE_LEMMAS] = [0] * len(chain_df)
        chain_df["tokens_context"] = [0.0] * len(chain_df)
        chain_df[MLTD] = [0.0] * len(chain_df)

        LOGGER.info("Calculating Phrasing Diversity...")
        for chain_id_value in tqdm(list(chain_df.index)):
            chain, dataset, split, language = chain_id_value.split("/")
            if split and not language:
                chain_mentions = [v for v in all_mentions_list if v[COREF_CHAIN] == chain and v[SPLIT] == split]
                chain_df.loc[chain_id_value, UNIQUE_LEMMAS] = len(
                    set([v.lower() for v in mentions_df[
                        (mentions_df[COREF_CHAIN] == chain) & (mentions_df[SPLIT] == split)][MENTION_HEAD_LEMMA].values]))
            elif language:
                chain_mentions = [v for v in all_mentions_list if v[COREF_CHAIN] == chain and v[LANGUAGE] == language]
                chain_df.loc[chain_id_value, UNIQUE_LEMMAS] = len(
                    set([v.lower() for v in mentions_df[
                        (mentions_df[COREF_CHAIN] == chain) & (mentions_df[LANGUAGE] == language)][MENTION_HEAD_LEMMA].values]))
            else:
                chain_mentions = [v for v in all_mentions_list if v[COREF_CHAIN] == chain]
                chain_df.loc[chain_id_value, UNIQUE_LEMMAS] = len(
                    set([v.lower() for v in mentions_df[mentions_df[COREF_CHAIN] == chain][MENTION_HEAD_LEMMA].values]))
            chain_df.loc[chain_id_value, PHRASING_DIVERSITY] = float(phrasing_diversity_calc(chain_mentions))
            chain_df.loc[chain_id_value, "tokens_context"] = np.mean([len(m[MENTION_CONTEXT]) for m in chain_mentions])
            token_from_selected_mentions = list(itertools.chain.from_iterable([m[TOKENS_TEXT] for m in chain_mentions]))
            chain_df.loc[chain_id_value, MLTD] = compute_mtld(token_from_selected_mentions)

        # form dataset as full and split into topics to process
        # per topic/subtopic in the dataset
        process_list = [(dataset, split, "", group_df)
                        for (dataset, split), group_df in mentions_df.groupby([DATASET_NAME, SPLIT])]
        # per language per topic
        if len(set(mentions_df[LANGUAGE].values)) > 1:
            process_list.extend([(dataset, "", language, group_df)
                             for (dataset, language), group_df in mentions_df.groupby([DATASET_NAME, LANGUAGE])])
        # full dataset
        process_list.extend([(dataset, "", "", dataset_df) for dataset, dataset_df in mentions_df.groupby([DATASET_NAME])])

        # collect statistics about the dataset
        for dataset, split, language, group_df in tqdm(process_list):
            coref_chains_entities = list(set(group_df[group_df[TYPE] == ENTITY][COREF_CHAIN].values))
            coref_chains_events = list(set(group_df[group_df[TYPE] == EVENT][COREF_CHAIN].values))
            coref_chains = list(set(group_df[COREF_CHAIN].values))
            if split and not language:
                tokens_len = len(df_conll[df_conll[SPLIT] == split])
            elif language:
                tokens_len = len(df_conll[df_conll[TOPIC_SUBTOPIC_DOC].str.contains(language)])
            else:
                tokens_len = len(df_conll)

            cross_subtopic_chains_df = group_df[[COREF_CHAIN, SUBTOPIC_ID, DOC_ID]].groupby([COREF_CHAIN, SUBTOPIC_ID]).count().reset_index()
            cross_subtopic_chains = 0
            cross_subtopic_mentions = 0
            for chain_id in set(cross_subtopic_chains_df[COREF_CHAIN]):
                ct_df = cross_subtopic_chains_df[cross_subtopic_chains_df[COREF_CHAIN] == chain_id]
                if len(ct_df) > 1:
                    cross_subtopic_chains += 1
                    cross_subtopic_mentions += np.sum(ct_df[DOC_ID].values)

            doc_len = len(set(group_df[CONLL_DOC_KEY].values))
            tokens_context_len = chain_df[chain_df[COREF_CHAIN].isin(coref_chains)]["tokens_context"].mean()

            # general statistics
            summary_dict = {
                DATASET_NAME: dataset,
                SPLIT: f'{split}',
                LANGUAGE: language,
                TOPICS: len(set(group_df[TOPIC_ID].values)),
                "subtopics": len(set(group_df[SUBTOPIC_ID].values)),
                "documents": doc_len,
                TOKENS: tokens_len,
                "tokens_context": round(tokens_context_len, 2),
                "mean_doc_size": round(tokens_len / doc_len, 2),
                COREF_CHAIN + "_all": len(coref_chains),
                COREF_CHAIN: len(coref_chains) - len(group_df[group_df[IS_SINGLETON]]),
                MENTIONS: len(group_df),
                "mean_mention_density": round(len(group_df) / doc_len, 2),
                SINGLETONS: len(group_df[group_df[IS_SINGLETON]]),
                "cross-subtopic-chains": cross_subtopic_chains,
                "cross-subtopic-mentions": cross_subtopic_mentions,
                f'{COREF_CHAIN}_{ENTITY}': len(coref_chains_entities),
                f'{COREF_CHAIN}_{EVENT}': len(coref_chains_events),
                f'{MENTIONS}_{ENTITY}': len(group_df[group_df[TYPE] == ENTITY]),
                f'{MENTIONS}_{EVENT}': len(group_df[group_df[TYPE] == EVENT]),
                f'{SINGLETONS}_{ENTITY}': len(group_df[(group_df[TYPE] == ENTITY) & group_df[IS_SINGLETON]]),
                f'{SINGLETONS}_{EVENT}': len(group_df[(group_df[TYPE] == EVENT) & group_df[IS_SINGLETON]]),
            }

            # various for, of lexical diversity that depend on the presence/absence of singletons
            for suff, filt_criteria in zip([ALL, WO_SINGL], [0, 1]):
                selected_chains_df = chain_df[(chain_df[MENTIONS] > filt_criteria) &
                                              (chain_df[COREF_CHAIN].isin(coref_chains)) & (chain_df[SPLIT] == split)
                                              & (chain_df[LANGUAGE] == language)]
                if not len(selected_chains_df):
                    continue
                summary_dict[AVERAGE_SIZE + suff] = round(np.mean(selected_chains_df[MENTIONS].values), 2)
                summary_dict[PHRASING_DIVERSITY + WEIGHTED + suff] = round(sum([row[PHRASING_DIVERSITY] * row[MENTIONS]
                                                                  for index, row in selected_chains_df.iterrows()]) / \
                                                                     sum(selected_chains_df[MENTIONS].values), 2)
                summary_dict[UNIQUE_LEMMAS + "_avg" + suff] = round(np.mean(selected_chains_df[UNIQUE_LEMMAS].values), 2)
                summary_dict[UNIQUE_LEMMAS + "_sum" + suff] = len(set(mentions_df[mentions_df[COREF_CHAIN].isin(list(selected_chains_df[COREF_CHAIN].values))][MENTION_HEAD_LEMMA].values))
                chains_use_lemma = []
                for head, group_df_lemma in mentions_df[mentions_df[COREF_CHAIN].isin(list(selected_chains_df[COREF_CHAIN].values))].groupby(MENTION_HEAD_LEMMA):
                    chains_use_lemma.append(len(set(group_df_lemma[COREF_CHAIN].values)))

                summary_dict["lexical_ambiguity" + suff] = round(np.mean(chains_use_lemma), 2)
                summary_dict[MLTD + suff] = round(sum([row[MLTD] * row[MENTIONS]
                                                                  for index, row in selected_chains_df.iterrows()]) / \
                                                                     sum(selected_chains_df[MENTIONS].values), 2)

            summary_df = pd.concat([summary_df, pd.DataFrame(summary_dict, index=[f'{dataset}\\{split}\\{language}'])], axis=0)
            
        chain_df_all = pd.concat([chain_df_all, chain_df], axis=0)
        
        # save the dataset statistics after each dataset
        chain_df_all.reset_index().to_csv(os.path.join(os.getcwd(), SUMMARY_FOLDER, chains_file_name))
        summary_df.to_csv(os.path.join(os.getcwd(), SUMMARY_FOLDER, f'{now_.strftime("%Y-%m-%d_%H-%M-%S")}_{SUMMARY_TOPICS_CSV}'))

    LOGGER.info(f'Summary computed over {len(selected_dir_to_summarize)} datasets ({str(selected_dir_to_summarize)}) '
                f'is completed.')
    return chains_file_name


def check_datasets(dataset_dict: dict):
    """
    Checks the datasets to comply with the requirements.
    Args:
        dataset_dict: a dictionary with a format {dataset: dataset_folder}

    """
    LOGGER.info("Verifying a structure of mentions files...")
    for dataset_name_orig, dataset_folder in dataset_dict.items():
        dataset_name = dataset_name_orig.split("-")[0]
        LOGGER.info(f"Verifying {dataset_name}")
        json_dict = {}

        for split in ["train", "val", "test"]:
            json_dict[split] = {}
            for file_name in [MENTIONS_ENTITIES_JSON, MENTIONS_EVENTS_JSON]:
                with open(os.path.join(dataset_folder, split, file_name), "r") as file:
                    mentions = json.load(file)

                if not len(mentions):
                    continue

                # check mention structure
                if split == "test":
                    mention = random.choices(mentions, k=1)
                    check_mention_attributes(mention[0], dataset_name)

                json_dict[split][file_name] = mentions

        mentions_df = pd.read_parquet(os.path.join(dataset_folder, MENTIONS_ALL_PARQUET), engine="pyarrow")
        # double check that the singletons were removed
        chain_df = pd.DataFrame(columns=[SPLIT, COREF_CHAIN, TOPIC_ID, SUBTOPIC_ID, MENTIONS])
        chain_df = pd.concat(
            [chain_df,
             mentions_df[[SPLIT, COREF_CHAIN, SUBTOPIC_ID, DOC_ID]].groupby([SPLIT, COREF_CHAIN, SUBTOPIC_ID]).count().rename(
                 columns={DOC_ID: MENTIONS}).reset_index()], axis=0)
        chain_df = pd.concat(
            [chain_df,
             mentions_df[[SPLIT, COREF_CHAIN, TOPIC_ID, DOC_ID]].groupby([SPLIT, COREF_CHAIN, TOPIC_ID]).count().rename(
                 columns={DOC_ID: MENTIONS}).reset_index()], axis=0)
        chain_df.fillna("", inplace=True)
        chain_df["composite_chain_id"] = chain_df.apply(
            lambda x: f'{x[COREF_CHAIN].replace("/", "-")}/{x[SPLIT]}/{x[TOPIC_ID]}/{x[SUBTOPIC_ID]}',
            axis=1)
        chain_df = chain_df.set_index("composite_chain_id")

        all_mentions = []
        global_resave = False
        for split, file_info in json_dict.items():
            non_singl_chains = chain_df[(chain_df[MENTIONS] > 1) & (chain_df[SPLIT] == split)][COREF_CHAIN].unique()

            # check same mention_types per chain
            chain_mention_type_dict = {}
            for chain_name in chain_df[chain_df[SPLIT] == split][COREF_CHAIN].unique():
                chain_local_df = mentions_df[(mentions_df[COREF_CHAIN] == chain_name)]
                if len(chain_local_df[MENTION_FULL_TYPE].unique()) > 1:
                    new_type = chain_local_df[[MENTION_FULL_TYPE, MENTION_ID]].groupby(MENTION_FULL_TYPE).count()[
                        MENTION_ID].idxmax()
                    LOGGER.info(f"Chain {chain_name} need unification of the mention type: {chain_local_df[MENTION_FULL_TYPE].unique()} -> {new_type}")
                    chain_mention_type_dict[chain_name] = new_type

            for file_name, mentions in file_info.items():
                resave = False
                for m_id, m in enumerate(mentions):
                    if m[COREF_CHAIN] in non_singl_chains and m[IS_SINGLETON]:
                        LOGGER.info(f"Found coref chain {m[COREF_CHAIN]} in {dataset_name}/{split}! Json {split}/{file_name} will be resaved.")
                        m[IS_SINGLETON] = False
                        resave = True

                    if m[COREF_CHAIN] not in non_singl_chains and not m[IS_SINGLETON]:
                        LOGGER.info(f"Found a singleton {m[COREF_CHAIN]} in {dataset_name}/{split}! Json {split}/{file_name} will be resaved.")
                        m[IS_SINGLETON] = True
                        resave = True

                    if m[COREF_CHAIN] in chain_mention_type_dict:
                        if m[MENTION_FULL_TYPE] != chain_mention_type_dict[m[COREF_CHAIN]] :
                            LOGGER.info(f"Mention {m[MENTION_ID]} need unification of the mention type: {m[MENTION_FULL_TYPE]} -> {chain_mention_type_dict[m[COREF_CHAIN]]}")
                            m[MENTION_FULL_TYPE] = chain_mention_type_dict[m[COREF_CHAIN]]
                            m[MENTION_TYPE] = chain_mention_type_dict[m[COREF_CHAIN]][:3]
                            resave = True

                if resave:
                    global_resave = resave
                    with open(os.path.join(dataset_folder, split, file_name), "w") as file:
                        json.dump(mentions, file)

                all_mentions.extend(mentions)

        if global_resave:
            all_mentions_ = [{
                attr: str(value) if type(value) == list else value for attr, value in mention.items()
            } for mention in all_mentions]
            df_all_mentions = pd.DataFrame(all_mentions_, index=[mention[MENTION_ID] for mention in all_mentions])
            df_all_mentions.to_parquet(os.path.join(dataset_folder, MENTIONS_ALL_PARQUET), engine="pyarrow")

        LOGGER.info(f"Dataset {dataset_name} is fine!")
    LOGGER.info("Verification is complete. ")


def evalualte_with_baselines(topic_level_datasets: List[str], datasets: dict = None, remove_singletons: bool = True, doc_whitelist: List[str] = None):
    summary_df = pd.DataFrame()
    chain_df_all = pd.DataFrame()
    # mentions_all_df = pd.DataFrame()
    now_ = datetime.now()
    topic_level_datasets_clean = []

    if datasets is None:
        for i, dataset in enumerate(list(DIRECTORIES_TO_SUMMARIZE)):
            print(f'{i}: {dataset.split("-")[0]}')

        input_str = input("List dataset IDs with comma separation which to include into the summary or print \"all\" to summarize all: ")
        if "all" in input_str:
            selected_dir_to_summarize = list(DIRECTORIES_TO_SUMMARIZE.items())
        else:
            selected_dataset_ids = [int(part.strip()) for part in input_str.split(',')]
            selected_dir_to_summarize = [list(DIRECTORIES_TO_SUMMARIZE.items())[i] for i in selected_dataset_ids]
    else:
        selected_dir_to_summarize = list(datasets.items())
    LOGGER.info(f'Selected dataset to summarize: {selected_dir_to_summarize}')

    # read annotated mentions and corresponding texts
    for dataset_name, dataset_folder in selected_dir_to_summarize:
        all_mentions_list = []
        mentions_df = pd.DataFrame()
        dataset_name_clean = dataset_name.split("-")[0]

        split_df = pd.DataFrame()
        split = "test"

        LOGGER.info(f'Reading files with mentions for {dataset_name} dataset...')
        for mention_type, file_name in zip([EVENT, ENTITY], [MENTIONS_EVENTS_JSON, MENTIONS_ENTITIES_JSON]):

            # read mentions
            full_filename = os.path.join(dataset_folder, split, file_name)
            LOGGER.info(f'Processing {full_filename}...')
            with open(full_filename, encoding='utf-8', mode='r') as file:
                mentions_read_list = json.load(file)

            mentions_read_list_clean = []

            for mention in mentions_read_list:
                # enforced unique mentions
                mention[MENTION_ID] = f'{mention[MENTION_ID]}_{shortuuid.uuid()[:6]}'
                # make sure that there is no backslashes
                mention[COREF_CHAIN] = mention[COREF_CHAIN].replace("/", "-")
                if LANGUAGE not in mention:
                    mention[LANGUAGE] = "english"
                mention[SPLIT] = split

                if doc_whitelist is not None:
                    if mention[DOC] not in doc_whitelist:
                        continue

                if remove_singletons:
                    if mention[IS_SINGLETON]:
                        continue

                mentions_read_list_clean.append(mention)

            df_tmp = pd.DataFrame(mentions_read_list_clean, index=list(range(len(mentions_read_list_clean))))
            df_tmp[TYPE] = [mention_type] * len(df_tmp)
            # kick out "prep" from the name
            df_tmp[DATASET_NAME] = [dataset_name_clean] * len(df_tmp)
            mentions_df = pd.concat([mentions_df, df_tmp], ignore_index=True, axis=0)
            all_mentions_list.extend(mentions_read_list_clean)
            if len(df_tmp):
                split_df = pd.concat([split_df, df_tmp[[CONLL_DOC_KEY, SPLIT]].drop_duplicates()])

        split_df.drop_duplicates(inplace=True)
        mentions_df.set_index(MENTION_ID, inplace=True)
        # calculate statistics about the chains

        # double check that the singletons were removed
        chain_df = pd.DataFrame(columns=[COREF_CHAIN, DATASET_NAME, TOPIC_ID, SUBTOPIC_ID, MENTIONS])
        chain_df = pd.concat(
            [chain_df, mentions_df[[COREF_CHAIN, DATASET_NAME, SUBTOPIC_ID, DOC_ID]].groupby([COREF_CHAIN, DATASET_NAME,
                                                                                        SUBTOPIC_ID]).count().rename(
                columns={DOC_ID: MENTIONS}).reset_index()], axis=0)
        chain_df = pd.concat(
            [chain_df, mentions_df[[COREF_CHAIN, DATASET_NAME, TOPIC_ID, DOC_ID]].groupby([COREF_CHAIN, DATASET_NAME,
                                                                                        TOPIC_ID]).count().rename(
                columns={DOC_ID: MENTIONS}).reset_index()], axis=0)
        chain_df.fillna("", inplace=True)
        chain_df["composite_chain_id"] = chain_df.apply(
            lambda x: f'{x[COREF_CHAIN].replace("/", "-")}/{x[DATASET_NAME]}/{x[TOPIC_ID]}/{x[SUBTOPIC_ID]}', axis=1)
        chain_df = chain_df.set_index("composite_chain_id")

        if remove_singletons:
            selected_chains = chain_df[chain_df[MENTIONS] > 1][COREF_CHAIN].unique()
        else:
            selected_chains = chain_df[COREF_CHAIN].unique()

        mentions_selected_df = mentions_df[mentions_df[COREF_CHAIN].isin(selected_chains)]
        if len(mentions_df) != len(mentions_selected_df):
            LOGGER.info("Good that you checked!")

        # per subtopic
        process_list = [(dataset, "", subtopic, "", dataset_df) for (dataset, subtopic), dataset_df in
                             mentions_selected_df.groupby([DATASET_NAME, SUBTOPIC_ID])]
        # per mention type
        if len(mentions_selected_df[TYPE].unique()) > 1:
            for (dataset, subtopic, mention_type), dataset_df in mentions_selected_df.groupby([DATASET_NAME, SUBTOPIC_ID, TYPE]):
                process_list.append((dataset, "", subtopic, mention_type, dataset_df))
        # all subtopic level
        # aggregated later
        # process_list.append((dataset_name_clean, "", "mean", mentions_selected_df))

        # per topic
        if dataset_name in topic_level_datasets:
            for (dataset, topic), dataset_df in mentions_selected_df.groupby([DATASET_NAME, TOPIC_ID]):
                process_list.append((dataset, topic, "", "", dataset_df))

            if len(mentions_selected_df[TYPE].unique()) > 1:
                for (dataset, topic, mention_type), dataset_df in mentions_selected_df.groupby([DATASET_NAME, TOPIC_ID, TYPE]):
                    process_list.append((dataset, topic, "", mention_type, dataset_df))
            # all topic level
            # aggregated later
            # process_list.append((dataset_name_clean, "mean", "", mentions_selected_df))

        # check the process list
        process_list_valid = []
        for i, setting in enumerate(process_list):
            if len(setting[4]) < 2:
                LOGGER.info(f"Setting {setting[:4]} has only one mention, skipped.")
            else:
                process_list_valid.append(setting)

        # collect statistics about the dataset
        for dataset, topic, subtopic, mention_type, group_df in tqdm(process_list_valid):

            # general statistics
            summary_dict = {
                DATASET_NAME: dataset,
                TOPIC_ID: topic,
                SUBTOPIC_ID: subtopic,
                TYPE: mention_type
            }

            selected_mentions = [v for v in all_mentions_list if v[MENTION_ID] in group_df.index.tolist()]
            if len(subtopic):
                conll_f1_dict = conll_lemma_baseline(selected_mentions, subtopics=True)
            else:
                # topic level
                conll_f1_dict = conll_lemma_baseline(selected_mentions,
                                                     subtopics=False)
            summary_dict.update(conll_f1_dict)
            summary_df = pd.concat([summary_df, pd.DataFrame(summary_dict, index=[f'{dataset}\\{topic}\\{subtopic}\\{mention_type}'])], axis=0)

        # average suptopic level
        subtopic_level_df = pd.DataFrame()
        for mention_type in ["", EVENT, ENTITY]:
            subtopic_level_series = summary_df[(summary_df[DATASET_NAME] == dataset_name_clean) & (summary_df[SUBTOPIC_ID].str.len() > 0) & (summary_df[TYPE] == mention_type)].drop(columns=[DATASET_NAME, TOPIC_ID, SUBTOPIC_ID, TYPE]).mean(axis=0)
            local_df = pd.DataFrame({f"{dataset_name_clean}//mean/{mention_type}": subtopic_level_series}).T
            local_df[DATASET_NAME] = dataset_name_clean
            local_df[SUBTOPIC_ID] = "mean"
            local_df[TYPE] = mention_type
            local_df[TOPIC_ID] = ""
            subtopic_level_df = pd.concat([subtopic_level_df, local_df])

            if len(mentions_selected_df[TYPE].unique()) == 1:
                # no need to recalculate if it is only one mention type
                local_df[TYPE] = mentions_selected_df[TYPE].unique()[0]
                subtopic_level_df = pd.concat([subtopic_level_df, local_df])
                break

        # average topic level
        topic_level_df = pd.DataFrame()
        if dataset_name in topic_level_datasets:
            for mention_type in ["", EVENT, ENTITY]:
                topic_level_series = summary_df[(summary_df[DATASET_NAME] == dataset_name_clean) & (summary_df[TOPIC_ID].str.len() > 0) & (summary_df[TYPE] == mention_type)].drop(columns=[DATASET_NAME, TOPIC_ID, SUBTOPIC_ID, TYPE]).mean(axis=0)
                local_df = pd.DataFrame({f"{dataset_name_clean}/mean//{mention_type}": topic_level_series}).T
                local_df[DATASET_NAME] = dataset_name_clean
                local_df[TOPIC_ID] = "mean"
                local_df[SUBTOPIC_ID] = ""
                local_df[TYPE] = mention_type
                topic_level_df = pd.concat([topic_level_df, local_df])

                if len(mentions_selected_df[TYPE].unique()) == 1:
                    # no need to recalculate if it is only one mention type
                    local_df[TYPE] = mentions_selected_df[TYPE].unique()[0]
                    topic_level_df = pd.concat([topic_level_df, local_df])
                    break

        summary_df = pd.concat([summary_df, subtopic_level_df, topic_level_df])
        summary_df.to_csv(os.path.join(os.getcwd(), SUMMARY_FOLDER, f'{now_.strftime("%Y-%m-%d_%H-%M-%S")}_conll_baseline.csv'))

    LOGGER.info(f'F1 CONLL computed over {len(selected_dir_to_summarize)} datasets ({str(selected_dir_to_summarize)}) '
                f'is completed.')


def create_doc_tsne_scatterplot(dataset_dict: dict, max_docs_dataset: int = 100):
    """
    Collects data and plots a scatterplot of tSNE representation of mentions' text.
        The original code belongs to https://gist.github.com/jpwahle/f9414b2ae85043225b10cd9e105d3b81
    # Copyright 2022 by Jan Philip Wahle, https://jpwahle.com/
    # All rights reserved.
    Args:
        dataset_dict: datasets to plot and the folders where the data located
    """
    df_list, dataset_name_list = [], []
    for dataset_name, folder_path in tqdm(dataset_dict.items(), desc="Reading data"):
        df = pd.read_parquet(os.path.join(folder_path, DOCUMENTS_ALL_PARQUET), engine="pyarrow")
        df_list.append(df)
        dataset_name_list.append(dataset_name.replace("-prep", ""))

    X, y = [], []
    stop_words = set(stopwords.words("english"))
    df_path = os.path.join(os.getcwd(), SUMMARY_FOLDER, "scatterplot_doc.csv")

    if not os.path.exists(df_path):

        for dataset_name, dataset_df in tqdm(zip(dataset_name_list, df_list),
                                             desc="Processing documents for tSNE", total=len(dataset_name_list)):
            selected_doc_ids = random.choices(dataset_df[TOPIC_SUBTOPIC_DOC].unique().tolist(), k=max_docs_dataset)
            selected_df = dataset_df[dataset_df[TOPIC_SUBTOPIC_DOC].isin(selected_doc_ids)]

            for topic_subtopic_doc, doc_df in selected_df.groupby(by=[TOPIC_SUBTOPIC_DOC]):
                y.append(dataset_name)
                tokens = []
                for t in doc_df[TOKEN].values:
                    if t in punctuation or t in stop_words:
                        continue
                    tokens.append(t)
                doc_text = " ".join(tokens)
                X.append(doc_text)

        vect = dask_ml.feature_extraction.text.HashingVectorizer()
        X_tfidf = vect.fit_transform(X)

        svd = TruncatedSVD(n_components=160, n_iter=9, random_state=42)
        X_svd = svd.fit_transform(X_tfidf)

        tsne = TSNE(
            perplexity=30,
            metric="euclidean",
            n_jobs=8,
            random_state=42,
            verbose=True,
        )

        LOGGER.info("Plotting documents")
        X_tsne = tsne.fit(X_svd)

        df = pd.DataFrame(X_tsne, columns=["x", "y"])
        df = df.merge(pd.DataFrame({"color": y}, dtype="category"), left_index=True, right_index=True)
        df.to_csv(df_path)
    else:
        df = pd.read_csv(df_path)

    # Create larger figure
    plt.figure(figsize=(12, 8))

    for dataset, group in df.groupby("color"):
        plt.scatter(
            group['x'].values,
            group['y'].values,
            label=CORRECTED_LABELS[dataset],
            color=COLORS.get(dataset, "#000000"),
            s=30
        )

    plt.xlabel("X")
    plt.ylabel("Y")

    # plt.title("tSNE representation of the CDCR mentions")

    # Larger legend markers
    plt.legend(markerscale=2, fontsize=13)

    # Save as high-resolution PNG (300 DPI)
    output_path = os.path.join(os.getcwd(), SUMMARY_FOLDER, "scatterplot_doc.png")
    plt.savefig(output_path, dpi=300)
    plt.close()

    LOGGER.info(f"Scatterplot of documents is saved to {output_path}")


def create_mention_tsne_scatterplot(dataset_dict: dict, max_mentions_dataset: int = 6300):
    """
    Collects data and plots a scatterplot of tSNE representation of documents' text.
    Args:
        dataset_dict: datasets to plot and the folders where the data located
    """
    df_list, dataset_name_list = [], []
    for dataset_name, folder_path in tqdm(dataset_dict.items(), desc="Reading data"):
        df = pd.read_parquet(os.path.join(folder_path, MENTIONS_ALL_PARQUET), engine="pyarrow")
        df_list.append(df)
        dataset_name_list.append(dataset_name.replace("-prep", ""))

    X, y = [], []
    save_path = os.path.join(os.getcwd(), SUMMARY_FOLDER, "scatterplot_mention_embedding.csv")

    if not os.path.exists(save_path):
        for dataset_name, dataset_df in tqdm(zip(dataset_name_list, df_list),
                                             desc="Processing documents for tSNE", total=len(dataset_name_list)):
            selected_doc_ids = random.choices(dataset_df[MENTION_ID].unique().tolist(), k=max_mentions_dataset)
            selected_df = dataset_df[dataset_df[MENTION_ID].isin(selected_doc_ids)]
            X.extend(selected_df[TOKENS_STR].values.tolist())
            y.extend([dataset_name] * len(selected_df))

        model = SentenceTransformer("intfloat/multilingual-e5-large")
        embeddings = model.encode(
            X,
            batch_size=16,
            convert_to_numpy=True,
            show_progress_bar=True,
            normalize_embeddings=True,
        )

        svd = TruncatedSVD(n_components=160, n_iter=9, random_state=42)
        X_svd = svd.fit_transform(embeddings)

        tsne = TSNE(
            perplexity=30,
            metric="euclidean",
            n_jobs=8,
            random_state=42,
            verbose=True,
        )

        LOGGER.info("Plotting mentions")
        X_tsne = tsne.fit(X_svd)
        df = pd.DataFrame(X_tsne, columns=["x", "y"])

        df = df.merge(pd.DataFrame({"color": y}, dtype="category"), left_index=True, right_index=True)
        df.to_csv(save_path)
    else:
        df = pd.read_csv(save_path)

    # Create larger figure
    plt.figure(figsize=(12, 8))

    for dataset, group in df.groupby("color"):
        plt.scatter(
            group["x"],
            group["y"],
            label=CORRECTED_LABELS[dataset],
            color=COLORS.get(dataset, "#000000"),
            s=5
        )

    plt.xlabel("X")
    plt.ylabel("Y")
    plt.xlim(-120, 120)
    plt.ylim(-120, 120)

    # Larger legend markers
    plt.legend(markerscale=3, fontsize=13)

    # Save as high-resolution PNG (300 DPI)
    output_path = os.path.join(os.getcwd(), SUMMARY_FOLDER, "scatterplot_mentions.png")
    plt.savefig(output_path, dpi=300)
    plt.close()

    # print separate datasets
    for dataset, group in df.groupby("color"):
        plt.figure(figsize=(12, 8))
        plt.scatter(
            group["x"],
            group["y"],
            label=CORRECTED_LABELS[dataset],
            color=COLORS.get(dataset, "#000000"),
            s=5
        )
        plt.xlabel("X")
        plt.ylabel("Y")
        plt.xlim(-120, 120)
        plt.ylim(-120, 120)
        plt.legend(fontsize=18, markerscale=3)
        output_path = os.path.join(os.getcwd(), SUMMARY_FOLDER, f"scatterplot_mentions_{dataset}.png")
        plt.savefig(output_path, dpi=300)
        plt.close()
        # plt.title("tSNE representation of the CDCR mentions")

    # print comparable datasets
    plt.figure(figsize=(12, 8))
    for dataset, group in df[df["color"].isin(["ECBplus", "ECBplusMETAm"])].groupby("color"):
        plt.scatter(
            group["x"],
            group["y"],
            label=CORRECTED_LABELS[dataset],
            color=COLORS.get(dataset, "#000000"),
            s=5
        )
        plt.xlim(-120, 120)
        plt.ylim(-120, 120)
        plt.xlabel("X")
        plt.ylabel("Y")
    plt.legend(fontsize=18, markerscale=3)
    output_path = os.path.join(os.getcwd(), SUMMARY_FOLDER, f"scatterplot_mentions_ecbplus_comparison.png")
    plt.savefig(output_path, dpi=300)
    plt.close()

    plt.figure(figsize=(12, 8))
    for dataset, group in df[df["color"].isin(["NP4E", "NIdent"])].groupby("color"):
        plt.scatter(
            group["x"],
            group["y"],
            label=CORRECTED_LABELS[dataset],
            color=COLORS.get(dataset, "#000000"),
            s=5
        )
        plt.xlim(-120, 120)
        plt.ylim(-120, 120)
        plt.xlabel("X")
        plt.ylabel("Y")
    plt.legend(fontsize=18, markerscale=3)
    output_path = os.path.join(os.getcwd(), SUMMARY_FOLDER, f"scatterplot_mentions_np4e_nident_comparison.png")
    plt.savefig(output_path, dpi=300)
    plt.close()

    LOGGER.info(f"Scatterplot of mentions is saved to {output_path}")


def mention_stat_analysis(dataset_dict: dict):
    """
    Aggregates basic stats on the POS, NER, and mention types.
    Args:
        dataset_dict: a dict of dataset names and a path to the dataset
    """
    pos_df = pd.DataFrame()
    ner_df = pd.DataFrame()
    type_df = pd.DataFrame()
    now_ = datetime.now()

    for dataset_name_orig, dataset_folder in dataset_dict.items():
        dataset_name = dataset_name_orig.split("-")[0]
        mentions_df = pd.read_parquet(os.path.join(dataset_folder, MENTIONS_ALL_PARQUET), engine="pyarrow")
        pos_local_df =  mentions_df[[MENTION_HEAD_POS, MENTION_ID]].groupby([MENTION_HEAD_POS]).count().T
        pos_local_df.index = [dataset_name]
        pos_df = pd.concat([pos_df, pos_local_df])

        mentions_df[TYPE] = [v.split("_")[0] for v in mentions_df[MENTION_FULL_TYPE].values]
        type_local_df = mentions_df[[TYPE, MENTION_ID]].groupby([TYPE]).count().T
        type_local_df.index = [dataset_name]
        type_df = pd.concat([type_df, type_local_df])

        ner_local_df = mentions_df[[MENTION_NER, MENTION_ID]].groupby([MENTION_NER]).count().T
        ner_local_df.index = [dataset_name]
        ner_df = pd.concat([ner_df, ner_local_df])

    pos_df.fillna(0, inplace=True)
    ner_df.fillna(0, inplace=True)
    type_df.fillna(0, inplace=True)

    output_path = os.path.join(os.getcwd(), SUMMARY_FOLDER)
    pos_df.to_csv(os.path.join(output_path, f'{now_.strftime("%Y-%m-%d_%H-%M-%S")}_pos.csv'))
    ner_df.to_csv(os.path.join(output_path, f'{now_.strftime("%Y-%m-%d_%H-%M-%S")}_ner.csv'))
    type_df.to_csv(os.path.join(output_path, f'{now_.strftime("%Y-%m-%d_%H-%M-%S")}_type.csv'))
    LOGGER.info(f"Stats about POS, NER, and mentions types are saved to  {output_path}")


def plot_histogram_lexical_diversity(file_path: str, bins_num: int = 30):
    from collections import Counter
    # Load the dataset
    df = pd.read_csv(file_path)
    df.fillna("", inplace=True)

    # Filter rows where split == ""
    df_filtered = df[df["split"].str.len() == 0]

    for measure_name in [PHRASING_DIVERSITY, MLTD]:
        # df_filtered = df[df["split"] == "test"]
        max_val = math.floor(df_filtered[measure_name].max())//2
        min_val = math.floor(df_filtered[measure_name].min())
        # max_val = max_val if (max_val - min_val) % bins_num == 0 else ((max_val - min_val) // bins_num + 1) * bins_num
        bins = np.linspace(min_val, max_val, bins_num + 1)

        hist_df = pd.DataFrame()
        for dataset_name, group in df_filtered.groupby("dataset"):
            # bins = np.linspace(all_values.min(), all_values.max(), 31)
            bin_indices = np.digitize(group[measure_name].values, bins)
            bin_dict = Counter(bin_indices)
            hist_df = pd.concat([hist_df, pd.DataFrame(bin_dict, index= [dataset_name]).T], axis=1)
        hist_df.fillna(0, inplace=True)
        hist_df = hist_df.sort_index()
        for i, bin in enumerate(bins):
            if i == 0:
                continue
            if i not in hist_df.index:
                hist_df = pd.concat([hist_df, pd.DataFrame(np.zeros(len(hist_df.columns)).reshape(1,-1), index=[i], columns = hist_df.columns)])
        hist_df = hist_df.sort_index()
        indexes = [f"[{bins[i-1]}..{bins[i]})"for i in range(1, len(bins))]
        indexes.append(f"[{bins[-1]}..")
        hist_df.index = indexes
        hist_df.to_csv(os.path.join(os.getcwd(), SUMMARY_FOLDER, f"histogram_{measure_name}.csv"))
    LOGGER.info(f"Data for histogram plots is saved to {os.path.join(os.getcwd(), SUMMARY_FOLDER)}")


if __name__ == '__main__':
    # name of datasets and the paths to their folder
    datasets = {
        NEWSWCL50: os.path.join(os.getcwd(), NEWSWCL50, OUTPUT_FOLDER_NAME),
        MEANTIME: os.path.join(os.getcwd(), MEANTIME, OUTPUT_FOLDER_NAME),
        NP4E: os.path.join(os.getcwd(), NP4E, OUTPUT_FOLDER_NAME),
        NIDENT: os.path.join(os.getcwd(), NIDENT, OUTPUT_FOLDER_NAME),
        GVC: os.path.join(os.getcwd(), GVC, OUTPUT_FOLDER_NAME),
        FCC: os.path.join(os.getcwd(), FCC, OUTPUT_FOLDER_NAME),
        CD2CR: os.path.join(os.getcwd(), CD2CR, OUTPUT_FOLDER_NAME),
        WEC_ENG: os.path.join(os.getcwd(), WEC_ENG, OUTPUT_FOLDER_NAME),
        CEREC: os.path.join(os.getcwd(), CEREC, OUTPUT_FOLDER_NAME),
        HYPERCOREF: os.path.join(os.getcwd(), HYPERCOREF, OUTPUT_FOLDER_NAME),
        ECB_PLUS: os.path.join(os.getcwd(), ECB_PLUS, OUTPUT_FOLDER_NAME),
        ECBPLUS_METAM: os.path.join(os.getcwd(), ECBPLUS_METAM, OUTPUT_FOLDER_NAME),
    }
    check_datasets(datasets)
    chains_info_filename = create_summary(datasets)
    plot_histogram_lexical_diversity(os.path.join(os.getcwd(), SUMMARY_FOLDER, chains_info_filename))
    evalualte_with_baselines(topic_level_datasets=[FCC, HYPERCOREF, MEANTIME, WEC_ENG, ECB_PLUS, ECBPLUS_METAM], datasets=datasets, remove_singletons=True)
    # evalualte_with_baselines(topic_level_datasets=[FCC, HYPERCOREF, MEANTIME, WEC_ENG, ECB_PLUS, ECBPLUS_METAM], datasets=datasets, remove_singletons=False)
    create_doc_tsne_scatterplot(datasets)
    create_mention_tsne_scatterplot(datasets)
    mention_stat_analysis(datasets)
